version: '3.8'
services:
  fastapi-app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: fastapi-dev
    ports:
      - "8000:8000"
    environment:
      - ENV=development
