sonar.projectKey=securetask
sonar.projectName=SecureTask
sonar.projectVersion=1.0

# Chemins des sources
sonar.sources=backend
sonar.tests=tests

# Langages
sonar.language=py
sonar.python.version=3

# Exclusions
sonar.exclusions=**/__pycache__/**,**/*.pyc,**/venv/**,**/env/**,**/reservations.db

# Tests (optionnel)
sonar.python.coverage.reportPaths=coverage.xml
sonar.python.xunit.reportPath=test-results.xml
